name: unit-test
description: "Runs the Unit Tests on GdUnit3 API"

inputs:
    test-includes:
        description: "The path to include tests to be run"
        required: true
    godot-bin:
        required: true

runs:
    using: composite

    steps:
        - name: "Unit Test Linux"
          if: ${{ runner.OS == 'Linux' }}
          env:
              GODOT_BIN: ${{ inputs.godot-bin }}
          shell: bash
          run: |
              "$GODOT_BIN" --headless --import --path .
              chmod +x addons/gdUnit4/runtest.sh
              xvfb-run --auto-servernum addons/gdUnit4/runtest.sh --add ${{ inputs.test-includes }} --continue --audio-driver Dummy --verbose
