extends Node


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
#func _ready():
#	pass # Replace with function body.

const refDict = {
	"cave.ogg": "res://audio/background/cave.ogg",
	"main.ogg": "res://audio/background/main.ogg",
	"pond.ogg": "res://audio/background/pond.ogg",
	"quantum.ogg": "res://audio/background/quantum.ogg",
	
	"back.wav": "res://audio/effects/back.wav",
	"next.wav": "res://audio/effects/next.wav",
	"select.wav": "res://audio/effects/back.wav",	
	
	"Lobby.tscn": "res://Scenes/Core/Lobby.tscn",
	"Quit_Scene.tscn": "res://Scenes/Core/Quit_Scene.tscn",
	"GAME_START.tscn": "res://Scenes/Core/GAME_START.tscn",
	"Title_Scene.tscn": "res://Scenes/Core/Title_Scene.tscn",
	"Menu_Scene.tscn": "res://Scenes/Core/Menu_Scene.tscn",
	"Chunk.tscn": "res://Scenes/Level_5_VirtualWorld/Chunk.tscn",
	
	
	"Agency.tscn": "res://Scenes/level_1_character_creation/Part1Agency.tscn",
	"CharacterCreation.tscn": "res://Scenes/level_1_character_creation/Part4CharacterCreation.tscn",
	"DominoWorld.tscn": "res://Scenes/Level_4_DominoWorld/DominoWorld.tscn",
	"Tutorial.tscn": "res://Scenes/Core/Tutorial.tscn",
	
	#"AgencyTutorial.tscn": "res://Scenes/Level_1_Agency/AgencyTutorial.tscn",
	"CharacterCreationTutorial.tscn": "res://Scenes/Level_2_CharacterCreation/CharacterCreationTutorial.tscn",
	"DominoWorldTutorial.tscn": "res://Scenes/Level_4_DominoWorld/DominoWorldTutorial.tscn",
	
	#"level1.tscn": "res://Scenes/Level_1_Agency/level1.tscn",
	#"level1_cont.tscn": "res://Scenes/Level_1_Agency/level1_cont.tscn",
	"LevelSelect.tscn": "res://_Unsure/LevelSelect.tscn",
	"Manager.tscn": "res://Scenes/Core/Manager.tscn",
	"Pond.tscn": "res://Scenes/Level_2_Pond/Pond.tscn",
	"Sandbox.tscn": "res://_Unsure/Sandbox.tscn",
	"Stone.tscn": "res://Scenes/Level_2_Pond/Stone.tscn",
	#"String.tscn": "res://Scenes/Level_1_Agency/String.tscn",
	"VW0.tscn": "res://Scenes/Level_5_VirtualWorld/VW0.tscn",
	
	"Parallax1.tscn": "res://Scenes/Parallax/Parallax1.tscn",
	"Parallax2.tscn": "res://Scenes/Parallax/Parallax2.tscn",
	"Parallax3.tscn": "res://Scenes/Parallax/Parallax3.tscn",
	
	"FootprintTile.gd": "res://Scenes/Level_4_DominoWorld/FootprintTile.gd",
	"FootprintTileRing.gd": "res://Scenes/Level_4_DominoWorld/FootprintTileRing.gd",
	"Tower.gd": "res://Scenes/Level_4_DominoWorld/Tower.gd",
	
	"front_hair/0.png": "res://UI/sprites/character_sprites/front_hair/0.png",
	"front_hair/1.png": "res://UI/sprites/character_sprites/front_hair/1.png",
	"front_hair/2.png": "res://UI/sprites/character_sprites/front_hair/2.png",
	"front_hair/3.png": "res://UI/sprites/character_sprites/front_hair/3.png",
	"front_hair/4.png": "res://UI/sprites/character_sprites/front_hair/4.png",
	"front_hair/5.png": "res://UI/sprites/character_sprites/front_hair/5.png",
	"front_hair/6.png": "res://UI/sprites/character_sprites/front_hair/6.png",
	"front_hair/7.png": "res://UI/sprites/character_sprites/front_hair/7.png",
	"front_hair/8.png": "res://UI/sprites/character_sprites/front_hair/8.png",
	"front_hair/9.png": "res://UI/sprites/character_sprites/front_hair/9.png",
	"front_hair/10.png": "res://UI/sprites/character_sprites/front_hair/10.png",
	"front_hair/11.png": "res://UI/sprites/character_sprites/front_hair/11.png",
	
	"back_hair/0.png": "res://UI/sprites/character_sprites/back_hair/0.png",
	"back_hair/1.png": "res://UI/sprites/character_sprites/back_hair/1.png",
	"back_hair/2.png": "res://UI/sprites/character_sprites/back_hair/2.png",
	"back_hair/3.png": "res://UI/sprites/character_sprites/back_hair/3.png",
	"back_hair/4.png": "res://UI/sprites/character_sprites/back_hair/4.png",
	"back_hair/5.png": "res://UI/sprites/character_sprites/back_hair/5.png",
	"back_hair/6.png": "res://UI/sprites/character_sprites/back_hair/6.png",
	"back_hair/7.png": "res://UI/sprites/character_sprites/back_hair/7.png",
	"back_hair/8.png": "res://UI/sprites/character_sprites/back_hair/8.png",
	"back_hair/9.png": "res://UI/sprites/character_sprites/back_hair/9.png",
	"back_hair/10.png": "res://UI/sprites/character_sprites/back_hair/10.png",
	"back_hair/11.png": "res://UI/sprites/character_sprites/back_hair/11.png",
	
	"bodies/0.png": "res://UI/sprites/character_sprites/bodies/0.png",
	"bodies/1.png": "res://UI/sprites/character_sprites/bodies/1.png",
	"bodies/2.png": "res://UI/sprites/character_sprites/bodies/2.png",
	"bodies/3.png": "res://UI/sprites/character_sprites/bodies/3.png",
	
	"clothes/0.png": "res://UI/sprites/character_sprites/clothes/0.png",
	"clothes/1.png": "res://UI/sprites/character_sprites/clothes/1.png",
	"clothes/2.png": "res://UI/sprites/character_sprites/clothes/2.png",
	"clothes/3.png": "res://UI/sprites/character_sprites/clothes/3.png",
	"clothes/4.png": "res://UI/sprites/character_sprites/clothes/4.png",
	
	"faces/0.png": "res://UI/sprites/character_sprites/faces/0.png",
	"faces/1.png": "res://UI/sprites/character_sprites/faces/1.png",
	"faces/2.png": "res://UI/sprites/character_sprites/faces/2.png",
	"faces/3.png": "res://UI/sprites/character_sprites/faces/3.png",
	
	"player_icons/basket.png": "res://UI/sprites/player_icons/basket.png",
	"player_icons/boat.png": "res://UI/sprites/player_icons/boat.png",
	"player_icons/bowandarrow.png": "res://UI/sprites/player_icons/bowandarrow.png",
	"player_icons/campfire.png": "res://UI/sprites/player_icons/campfire.png",
	"player_icons/fire.png": "res://UI/sprites/player_icons/fire.png",
	"player_icons/spear.png": "res://UI/sprites/player_icons/spear.png",
	"player_icons/stone.png": "res://UI/sprites/player_icons/stone.png",
	"player_icons/sun.png": "res://UI/sprites/player_icons/sun.png",
	"player_icons/sunshine.png": "res://UI/sprites/player_icons/sunshine.png",
	"player_icons/wheel.png": "res://UI/sprites/player_icons/wheel.png",
	
	"dominoes/00.png": "res://UI/sprites/dominoes/00.png",
	"dominoes/01.png": "res://UI/sprites/dominoes/01.png",
	"dominoes/02.png": "res://UI/sprites/dominoes/02.png",
	"dominoes/03.png": "res://UI/sprites/dominoes/03.png",
	"dominoes/04.png": "res://UI/sprites/dominoes/04.png",
	"dominoes/05.png": "res://UI/sprites/dominoes/05.png",
	"dominoes/06.png": "res://UI/sprites/dominoes/06.png",
	"dominoes/07.png": "res://UI/sprites/dominoes/07.png",
	"dominoes/08.png": "res://UI/sprites/dominoes/08.png",
	"dominoes/09.png": "res://UI/sprites/dominoes/09.png",
	"dominoes/11.png": "res://UI/sprites/dominoes/11.png",
	"dominoes/12.png": "res://UI/sprites/dominoes/12.png",
	"dominoes/13.png": "res://UI/sprites/dominoes/13.png",
	"dominoes/14.png": "res://UI/sprites/dominoes/14.png",
	"dominoes/15.png": "res://UI/sprites/dominoes/15.png",
	"dominoes/16.png": "res://UI/sprites/dominoes/16.png",
	"dominoes/17.png": "res://UI/sprites/dominoes/17.png",
	"dominoes/18.png": "res://UI/sprites/dominoes/18.png",
	"dominoes/19.png": "res://UI/sprites/dominoes/19.png",
	"dominoes/22.png": "res://UI/sprites/dominoes/22.png",
	"dominoes/23.png": "res://UI/sprites/dominoes/23.png",
	"dominoes/24.png": "res://UI/sprites/dominoes/24.png",
	"dominoes/25.png": "res://UI/sprites/dominoes/25.png",
	"dominoes/26.png": "res://UI/sprites/dominoes/26.png",
	"dominoes/27.png": "res://UI/sprites/dominoes/27.png",
	"dominoes/28.png": "res://UI/sprites/dominoes/28.png",
	"dominoes/29.png": "res://UI/sprites/dominoes/29.png",
	"dominoes/33.png": "res://UI/sprites/dominoes/33.png",
	"dominoes/34.png": "res://UI/sprites/dominoes/34.png",
	"dominoes/35.png": "res://UI/sprites/dominoes/35.png",
	"dominoes/36.png": "res://UI/sprites/dominoes/36.png",
	"dominoes/37.png": "res://UI/sprites/dominoes/37.png",
	"dominoes/38.png": "res://UI/sprites/dominoes/38.png",
	"dominoes/39.png": "res://UI/sprites/dominoes/39.png",
	"dominoes/44.png": "res://UI/sprites/dominoes/44.png",
	"dominoes/45.png": "res://UI/sprites/dominoes/45.png",
	"dominoes/46.png": "res://UI/sprites/dominoes/46.png",
	"dominoes/47.png": "res://UI/sprites/dominoes/47.png",
	"dominoes/48.png": "res://UI/sprites/dominoes/48.png",
	"dominoes/49.png": "res://UI/sprites/dominoes/49.png",
	"dominoes/55.png": "res://UI/sprites/dominoes/55.png",
	"dominoes/56.png": "res://UI/sprites/dominoes/56.png",
	"dominoes/57.png": "res://UI/sprites/dominoes/57.png",
	"dominoes/58.png": "res://UI/sprites/dominoes/58.png",
	"dominoes/59.png": "res://UI/sprites/dominoes/59.png",
	"dominoes/66.png": "res://UI/sprites/dominoes/66.png",
	"dominoes/67.png": "res://UI/sprites/dominoes/67.png",
	"dominoes/68.png": "res://UI/sprites/dominoes/68.png",
	"dominoes/69.png": "res://UI/sprites/dominoes/69.png",
	"dominoes/77.png": "res://UI/sprites/dominoes/77.png",
	"dominoes/78.png": "res://UI/sprites/dominoes/78.png",
	"dominoes/79.png": "res://UI/sprites/dominoes/79.png",
	"dominoes/88.png": "res://UI/sprites/dominoes/88.png",
	"dominoes/89.png": "res://UI/sprites/dominoes/89.png",
	"dominoes/99.png": "res://UI/sprites/dominoes/99.png",
	
	"ConvexHexagon1.png": "res://UI/sprites/footprint_tiles/ConvexHexagon1.png",
	"ConvexHexagon2.png": "res://UI/sprites/footprint_tiles/ConvexHexagon2.png",
	"Trapezoid.png": "res://UI/sprites/footprint_tiles/Trapezoid.png",
	"Campfire.png": "res://UI/sprites/footprint_tiles/Campfire.png",
	"Dog.png": "res://UI/sprites/footprint_tiles/Dog.png",
	"Bowl.png": "res://UI/sprites/footprint_tiles/Bowl.png",
	"Ship.png": "res://UI/sprites/footprint_tiles/Ship.png",
	"Book.png": "res://UI/sprites/footprint_tiles/Book.png",
	"Car.png": "res://UI/sprites/footprint_tiles/Car.png",
	"Domino1.png": "res://UI/sprites/footprint_tiles/Domino1.png",
	"Domino2.png": "res://UI/sprites/footprint_tiles/Domino2.png",
	"Domino3.png": "res://UI/sprites/footprint_tiles/Domino3.png",
	"Domino4.png": "res://UI/sprites/footprint_tiles/Domino4.png",
	"Domino5.png": "res://UI/sprites/footprint_tiles/Domino5.png",
	"Domino6.png": "res://UI/sprites/footprint_tiles/Domino6.png",
	"Domino7.png": "res://UI/sprites/footprint_tiles/Domino7.png",
	"Domino8.png": "res://UI/sprites/footprint_tiles/Domino8.png",
	"Domino9.png": "res://UI/sprites/footprint_tiles/Domino9.png",
	
	"new_spatialmaterial.tres": "res://UI/sprites/new_spatialmaterial.tres",
}

func get_reference(ref_key):
	return refDict[ref_key]
