extends Node


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
#func _ready():
#	pass # Replace with function body.

const refDict = {
	"cave.ogg": "res://audio/background/cave.ogg",
	"main.ogg": "res://audio/background/main.ogg",
	"pond.ogg": "res://audio/background/pond.ogg",
	"quantum.ogg": "res://audio/background/quantum.ogg",
	
	"back.wav": "res://audio/effects/back.wav",
	"next.wav": "res://audio/effects/next.wav",
	"select.wav": "res://audio/effects/back.wav",	
	
	"Lobby.tscn": "res://Scenes/Core/Lobby.tscn",
	"Quit_Scene.tscn": "res://Scenes/Core/Quit_Scene.tscn",
	"GAME_START.tscn": "res://Scenes/Core/GAME_START.tscn",
	"Title_Scene.tscn": "res://Scenes/Core/Title_Scene.tscn",
	"Menu_Scene.tscn": "res://Scenes/Core/Menu_Scene.tscn",
	"Chunk.tscn": "res://Scenes/Level_5_VirtualWorld/Chunk.tscn",
	
	
	"Agency.tscn": "res://Scenes/Level_1_Agency/Agency.tscn",
	"CharacterCreation.tscn": "res://Scenes/Level_2_CharacterCreation/CharacterCreation.tscn",
	"DominoWorld.tscn": "res://Scenes/Level_4_DominoWorld/DominoWorld.tscn",
	"Tutorial.tscn": "res://Scenes/Core/Tutorial.tscn",
	
	"AgencyTutorial.tscn": "res://Scenes/Level_1_Agency/AgencyTutorial.tscn",
	"CharacterCreationTutorial.tscn": "res://Scenes/Level_2_CharacterCreation/CharacterCreationTutorial.tscn",
	"DominoWorldTutorial.tscn": "res://Scenes/Level_4_DominoWorld/DominoWorldTutorial.tscn",
	
	"level1.tscn": "res://Scenes/Level_1_Agency/level1.tscn",
	"level1_cont.tscn": "res://Scenes/Level_1_Agency/level1_cont.tscn",
	"LevelSelect.tscn": "res://_Unsure/LevelSelect.tscn",
	"Manager.tscn": "res://Scenes/Core/Manager.tscn",
	"Pond.tscn": "res://Scenes/Level_3_Pond/Pond.tscn",
	"Sandbox.tscn": "res://_Unsure/Sandbox.tscn",
	"Stone.tscn": "res://Scenes/Level_3_Pond/Stone.tscn",
	"String.tscn": "res://Scenes/Level_1_Agency/String.tscn",
	"VW0.tscn": "res://Scenes/Level_5_VirtualWorld/VW0.tscn",
	
	"Parallax1.tscn": "res://Scenes/Parallax/Parallax1.tscn",
	"Parallax2.tscn": "res://Scenes/Parallax/Parallax2.tscn",
	"Parallax3.tscn": "res://Scenes/Parallax/Parallax3.tscn",
	
	"FootprintTile.gd": "res://Scenes/Level_4_DominoWorld/FootprintTile.gd",
	"FootprintTileRing.gd": "res://Scenes/Level_4_DominoWorld/FootprintTileRing.gd",
	"Tower.gd": "res://Scenes/Level_4_DominoWorld/Tower.gd",
	
	"front_hair/0.png": "res://UI/sprites/character_sprites/front_hair/0.png",
	"front_hair/1.png": "res://UI/sprites/character_sprites/front_hair/1.png",
	"front_hair/2.png": "res://UI/sprites/character_sprites/front_hair/2.png",
	"front_hair/3.png": "res://UI/sprites/character_sprites/front_hair/3.png",
	"front_hair/4.png": "res://UI/sprites/character_sprites/front_hair/4.png",
	"front_hair/5.png": "res://UI/sprites/character_sprites/front_hair/5.png",
	"front_hair/6.png": "res://UI/sprites/character_sprites/front_hair/6.png",
	"front_hair/7.png": "res://UI/sprites/character_sprites/front_hair/7.png",
	"front_hair/8.png": "res://UI/sprites/character_sprites/front_hair/8.png",
	"front_hair/9.png": "res://UI/sprites/character_sprites/front_hair/9.png",
	"front_hair/10.png": "res://UI/sprites/character_sprites/front_hair/10.png",
	"front_hair/11.png": "res://UI/sprites/character_sprites/front_hair/11.png",
	
	"back_hair/0.png": "res://UI/sprites/character_sprites/back_hair/0.png",
	"back_hair/1.png": "res://UI/sprites/character_sprites/back_hair/1.png",
	"back_hair/2.png": "res://UI/sprites/character_sprites/back_hair/2.png",
	"back_hair/3.png": "res://UI/sprites/character_sprites/back_hair/3.png",
	"back_hair/4.png": "res://UI/sprites/character_sprites/back_hair/4.png",
	"back_hair/5.png": "res://UI/sprites/character_sprites/back_hair/5.png",
	"back_hair/6.png": "res://UI/sprites/character_sprites/back_hair/6.png",
	"back_hair/7.png": "res://UI/sprites/character_sprites/back_hair/7.png",
	"back_hair/8.png": "res://UI/sprites/character_sprites/back_hair/8.png",
	"back_hair/9.png": "res://UI/sprites/character_sprites/back_hair/9.png",
	"back_hair/10.png": "res://UI/sprites/character_sprites/back_hair/10.png",
	"back_hair/11.png": "res://UI/sprites/character_sprites/back_hair/11.png",
	
	"bodies/0.png": "res://UI/sprites/character_sprites/bodies/0.png",
	"bodies/1.png": "res://UI/sprites/character_sprites/bodies/1.png",
	"bodies/2.png": "res://UI/sprites/character_sprites/bodies/2.png",
	"bodies/3.png": "res://UI/sprites/character_sprites/bodies/3.png",
	
	"clothes/0.png": "res://UI/sprites/character_sprites/clothes/0.png",
	"clothes/1.png": "res://UI/sprites/character_sprites/clothes/1.png",
	"clothes/2.png": "res://UI/sprites/character_sprites/clothes/2.png",
	"clothes/3.png": "res://UI/sprites/character_sprites/clothes/3.png",
	"clothes/4.png": "res://UI/sprites/character_sprites/clothes/4.png",
	
	"faces/0.png": "res://UI/sprites/character_sprites/faces/0.png",
	"faces/1.png": "res://UI/sprites/character_sprites/faces/1.png",
	"faces/2.png": "res://UI/sprites/character_sprites/faces/2.png",
	"faces/3.png": "res://UI/sprites/character_sprites/faces/3.png",
	
	"player_icons/basket.png": "res://UI/sprites/player_icons/basket.png",
	"player_icons/boat.png": "res://UI/sprites/player_icons/boat.png",
	"player_icons/bowandarrow.png": "res://UI/sprites/player_icons/bowandarrow.png",
	"player_icons/campfire.png": "res://UI/sprites/player_icons/campfire.png",
	"player_icons/fire.png": "res://UI/sprites/player_icons/fire.png",
	"player_icons/spear.png": "res://UI/sprites/player_icons/spear.png",
	"player_icons/stone.png": "res://UI/sprites/player_icons/stone.png",
	"player_icons/sun.png": "res://UI/sprites/player_icons/sun.png",
	"player_icons/sunshine.png": "res://UI/sprites/player_icons/sunshine.png",
	"player_icons/wheel.png": "res://UI/sprites/player_icons/wheel.png",
	
	"dominos/00.png": "res://UI/sprites/dominos/00.png",
	"dominos/01.png": "res://UI/sprites/dominos/01.png",
	"dominos/02.png": "res://UI/sprites/dominos/02.png",
	"dominos/03.png": "res://UI/sprites/dominos/03.png",
	"dominos/04.png": "res://UI/sprites/dominos/04.png",
	"dominos/05.png": "res://UI/sprites/dominos/05.png",
	"dominos/06.png": "res://UI/sprites/dominos/06.png",
	"dominos/07.png": "res://UI/sprites/dominos/07.png",
	"dominos/08.png": "res://UI/sprites/dominos/08.png",
	"dominos/09.png": "res://UI/sprites/dominos/09.png",
	"dominos/11.png": "res://UI/sprites/dominos/11.png",
	"dominos/12.png": "res://UI/sprites/dominos/12.png",
	"dominos/13.png": "res://UI/sprites/dominos/13.png",
	"dominos/14.png": "res://UI/sprites/dominos/14.png",
	"dominos/15.png": "res://UI/sprites/dominos/15.png",
	"dominos/16.png": "res://UI/sprites/dominos/16.png",
	"dominos/17.png": "res://UI/sprites/dominos/17.png",
	"dominos/18.png": "res://UI/sprites/dominos/18.png",
	"dominos/19.png": "res://UI/sprites/dominos/19.png",
	"dominos/22.png": "res://UI/sprites/dominos/22.png",
	"dominos/23.png": "res://UI/sprites/dominos/23.png",
	"dominos/24.png": "res://UI/sprites/dominos/24.png",
	"dominos/25.png": "res://UI/sprites/dominos/25.png",
	"dominos/26.png": "res://UI/sprites/dominos/26.png",
	"dominos/27.png": "res://UI/sprites/dominos/27.png",
	"dominos/28.png": "res://UI/sprites/dominos/28.png",
	"dominos/29.png": "res://UI/sprites/dominos/29.png",
	"dominos/33.png": "res://UI/sprites/dominos/33.png",
	"dominos/34.png": "res://UI/sprites/dominos/34.png",
	"dominos/35.png": "res://UI/sprites/dominos/35.png",
	"dominos/36.png": "res://UI/sprites/dominos/36.png",
	"dominos/37.png": "res://UI/sprites/dominos/37.png",
	"dominos/38.png": "res://UI/sprites/dominos/38.png",
	"dominos/39.png": "res://UI/sprites/dominos/39.png",
	"dominos/44.png": "res://UI/sprites/dominos/44.png",
	"dominos/45.png": "res://UI/sprites/dominos/45.png",
	"dominos/46.png": "res://UI/sprites/dominos/46.png",
	"dominos/47.png": "res://UI/sprites/dominos/47.png",
	"dominos/48.png": "res://UI/sprites/dominos/48.png",
	"dominos/49.png": "res://UI/sprites/dominos/49.png",
	"dominos/55.png": "res://UI/sprites/dominos/55.png",
	"dominos/56.png": "res://UI/sprites/dominos/56.png",
	"dominos/57.png": "res://UI/sprites/dominos/57.png",
	"dominos/58.png": "res://UI/sprites/dominos/58.png",
	"dominos/59.png": "res://UI/sprites/dominos/59.png",
	"dominos/66.png": "res://UI/sprites/dominos/66.png",
	"dominos/67.png": "res://UI/sprites/dominos/67.png",
	"dominos/68.png": "res://UI/sprites/dominos/68.png",
	"dominos/69.png": "res://UI/sprites/dominos/69.png",
	"dominos/77.png": "res://UI/sprites/dominos/77.png",
	"dominos/78.png": "res://UI/sprites/dominos/78.png",
	"dominos/79.png": "res://UI/sprites/dominos/79.png",
	"dominos/88.png": "res://UI/sprites/dominos/88.png",
	"dominos/89.png": "res://UI/sprites/dominos/89.png",
	"dominos/99.png": "res://UI/sprites/dominos/99.png",
	
	"ConvexHexagon1.png": "res://UI/sprites/footprint_tiles/ConvexHexagon1.png",
	"ConvexHexagon2.png": "res://UI/sprites/footprint_tiles/ConvexHexagon2.png",
	"Trapezoid.png": "res://UI/sprites/footprint_tiles/Trapezoid.png",
	"Campfire.png": "res://UI/sprites/footprint_tiles/Campfire.png",
	"Dog.png": "res://UI/sprites/footprint_tiles/Dog.png",
	"Bowl.png": "res://UI/sprites/footprint_tiles/Bowl.png",
	"Ship.png": "res://UI/sprites/footprint_tiles/Ship.png",
	"Book.png": "res://UI/sprites/footprint_tiles/Book.png",
	"Car.png": "res://UI/sprites/footprint_tiles/Car.png",
	"Domino1.png": "res://UI/sprites/footprint_tiles/Domino1.png",
	"Domino2.png": "res://UI/sprites/footprint_tiles/Domino2.png",
	"Domino3.png": "res://UI/sprites/footprint_tiles/Domino3.png",
	"Domino4.png": "res://UI/sprites/footprint_tiles/Domino4.png",
	"Domino5.png": "res://UI/sprites/footprint_tiles/Domino5.png",
	"Domino6.png": "res://UI/sprites/footprint_tiles/Domino6.png",
	"Domino7.png": "res://UI/sprites/footprint_tiles/Domino7.png",
	"Domino8.png": "res://UI/sprites/footprint_tiles/Domino8.png",
	"Domino9.png": "res://UI/sprites/footprint_tiles/Domino9.png",
	
	"new_spatialmaterial.tres": "res://UI/sprites/new_spatialmaterial.tres",
}

func get_reference(ref_key):
	return refDict[ref_key]
#	pass
